version: "3.3"
services:
  employee:
    build:
      context: apps/employee-service
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/employees
      SPRING_DATASOURCE_USERNAME: employees
      SPRING_DATASOURCE_PASSWORD: employees
  employee-front-end:
    build:
      context: apps/employee-front-end
    ports:
      - 4200:80
  db:
    build: tools/postgresql
    ports:
      - 15432:5432
    volumes:
      - postgressVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: employees,employees-test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
volumes:
  postgressVolume: